# Generated by Django 4.0.2 on 2022-02-10 02:14

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZodioscopeDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_range', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('sign', models.CharField(blank=True, max_length=15)),
                ('current_date', models.DateTimeField()),
                ('description', models.TextField()),
                ('compatibility', models.CharField(blank=True, max_length=15)),
                ('mood', models.CharField(blank=True, max_length=15)),
                ('color', models.CharField(blank=True, max_length=15)),
                ('lucky_number', models.IntegerField(blank=True)),
                ('lucky_time', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ZodioscopeDailyAdmin',
            fields=[
                ('zodioscopedaily_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='zodioscope.zodioscopedaily')),
            ],
            bases=('zodioscope.zodioscopedaily',),
        ),
        migrations.AddConstraint(
            model_name='zodioscopedaily',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('date_range', '&&')], name='exclude_overlap'),
        ),
    ]
