# Generated by Django 4.0.2 on 2022-02-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodioscope', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='current_date',
            field=models.DateField(),
        ),
    ]
