# Generated by Django 4.0.2 on 2022-02-10 06:12

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodioscope', '0002_alter_zodioscopedaily_current_date'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zodioscopedaily',
            name='exclude_overlap',
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='current_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='zodioscopedaily',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('date_range', '&&')], name='include_overlap'),
        ),
    ]
