# Generated by Django 4.0.2 on 2022-02-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodioscope', '0003_remove_zodioscopedaily_exclude_overlap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='compatibility',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='current_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='lucky_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='lucky_time',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='mood',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='sign',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
