# Generated by Django 4.0.2 on 2022-02-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zodioscope', '0004_alter_zodioscopedaily_color_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='zodioscopedaily',
            name='include_overlap',
        ),
        migrations.AlterField(
            model_name='zodioscopedaily',
            name='current_date',
            field=models.DateField(),
        ),
    ]
